[helpers]

[git.files]
".gitconfig" = "~/.gitconfig"

[neovim.files]
nvim = "~/.config/nvim"
"fish/conf.d/neovim.fish" = "~/.config/fish/conf.d/neovim.fish"

[wezterm.files]
wezterm = "~/.config/wezterm"

[kitty.files]
kitty = "~/.config/kitty"

[rofi.files]
rofi = "~/.config/rofi"

[waybar.files]
waybar = "~/.config/waybar"

[wpaperd.files]
wpaperd = "~/.config/wpaperd"

[hyprland]
depends = ["rofi", "waybar", "wpaperd"]

[hyprland.files]
hypr = "~/.config/hypr"

[niri]
depends = ["rofi", "waybar", "wpaperd"]

[niri.files]
niri = "~/.config/niri"

[yabai.files]
yabai = "~/.config/yabai"
skhd = "~/.config/skhd"

[tmux.files]
".tmux.conf" = "~/.tmux.conf"

[fish.files]
"fish/config.fish" = "~/.config/fish/config.fish"
"fish/conf.d/0-profile.fish" = "~/.config/fish/conf.d/0-profile.fish"

[nushell.files]
nushell = "~/.config/nushell"

[posh.files]
"Microsoft.PowerShell_profile.ps1" = ""

[colima.files]
"fish/conf.d/colima.fish" = "~/.config/fish/conf.d/colima.fish"

[rustup.files]
"fish/conf.d/0-rustup.fish" = "~/.config/fish/conf.d/0-rustup.fish"

[flyctl.files]
"fish/conf.d/flyctl.fish" = "~/.config/fish/conf.d/flyctl.fish"

[eza.files]
"fish/conf.d/eza.fish" = "~/.config/fish/conf.d/eza.fish"

[fish-air.files]
"fish/conf.d/0-air-profile.fish" = "~/.config/fish/conf.d/0-air-profile.fish" 

[fnm.files]
"fish/conf.d/fnm.fish" = "~/.config/fish/conf.d/fnm.fish"

[go.files]
"fish/conf.d/go.fish" = "~/.config/fish/conf.d/go.fish"

[juliaup.files]
"fish/conf.d/juliaup.fish" = "~/.config/fish/conf.d/juliaup.fish"

[rg.files]
"fish/conf.d/rg.fish" = "~/.config/fish/conf.d/rg.fish"

[vcpkg.files]
"fish/conf.d/vcpkg.fish" = "~/.config/fish/conf.d/vcpkg.fish"

[xmake.files]
"fish/conf.d/xmake.fish" = "~/.config/fish/conf.d/xmake.fish"

[zoxide.files]
"fish/conf.d/zoxide.fish" = "~/.config/fish/conf.d/zoxide.fish"

[ghcup.files]
"fish/conf.d/ghcup.fish" = "~/.config/fish/conf.d/ghcup.fish"

[yazi.files]
yazi = "~/.config/yazi"
"fish/conf.d/yazi.fish" = "~/.config/fish/conf.d/yazi.fish"

[starship.files]
"fish/conf.d/starship.fish" = "~/.config/fish/conf.d/starship.fish"
starship = "~/.config/starship"

[zed.files]
"zed/settings.json" = "~/.config/zed/settings.json"
"zed/keymap.json" = "~/.config/zed/keymap.json"

[unix-cli]
depends = [
    "eza",
    "fish",
    "flyctl",
    "fnm",
    "ghcup",
    "git",
    "go",
    "juliaup",
    "neovim",
    "rg",
    "rustup",
    "starship",
    "tmux",
    "vcpkg",
    "xmake",
    "yazi",
    "zoxide",
]

[default]
depends = []

[macbook-air]
depends = [
    "fish-air",
    "unix-cli",
    "wezterm",
    "yabai",
    "zed",
]

[einstein-linux]
depends = [
    "niri",
    "unix-cli",
    "wezterm",
    "zed",
]

[ryzenpc-windows]
depends = [
    "git",
    "neovim",
    "nushell",
    "posh",
    "wezterm",
]

[settings]
default_target_type = "automatic"
